version: '3.8'

services:
  internet-routing-app:
    build: .
    container_name: internet-routing
    ports:
      - "3838:3838"
    volumes:
      - ./data-raw:/app/data-raw
    restart: unless-stopped