version: '3.8'

services:
  shiny-app:
    image: threathunting9-internet-routing-app:latest
    container_name: internet-routing-app
    ports:
      - "8181:3838"  
    restart: unless-stopped
    volumes:
      - ./data:/app/data  # если нужно монтировать данные
    stdin_open: true
    tty: true